// Package isp holds the catalog of access networks (mobile operators, fixed
// and wireless ISPs, satellite providers) a client's configs can be locked to,
// together with the IP prefixes each of them announces.
//
// data/catalog.json is generated by tools/ispgen/generate.py from public
// routing data: RIPE NCC's asn.txt for the AS -> organisation mapping and
// ipverse/asn-ip for the announced prefixes. It covers every Iranian
// organisation that actually routes traffic plus the global satellite
// operators, and is embedded in the binary so a fresh panel works offline.
package isp

import (
	_ "embed"
	"encoding/json"
	"errors"
	"net/netip"
	"sort"
	"strings"
	"sync"
)

// All is the pseudo-id meaning "every network is allowed". It is always the
// first entry offered by the UI and is never stored on a client.
const All = "all"

// Kind groups catalog entries in the UI.
type Kind string

const (
	KindMobile    Kind = "mobile"
	KindFixed     Kind = "fixed"
	KindWireless  Kind = "wireless"
	KindSatellite Kind = "satellite"
	KindOther     Kind = "other"
)

// ISP is one selectable access network.
type ISP struct {
	ID     string   `json:"id"`
	NameEN string   `json:"nameEn"`
	NameFA string   `json:"nameFa"`
	Kind   Kind     `json:"kind"`
	ASNs   []uint32 `json:"asns"`
	// Prefixes is how many IP ranges are known for this network. Zero means the
	// lock cannot be enforced for it (see Enforceable).
	Prefixes int `json:"prefixes"`
}

// Enforceable reports whether selecting this network restricts anything. An
// entry without prefixes — typically an MVNO riding entirely on its host
// operator's address space — is shown as unavailable rather than silently
// behaving like "all".
func (i ISP) Enforceable() bool { return i.Prefixes > 0 }

//go:embed data/catalog.json
var catalogJSON []byte

type rawEntry struct {
	ID     string   `json:"id"`
	NameFA string   `json:"nameFa"`
	NameEN string   `json:"nameEn"`
	Kind   Kind     `json:"kind"`
	ASNs   []uint32 `json:"asns"`
	V4     []string `json:"v4"`
	V6     []string `json:"v6"`
}

type rawCatalog struct {
	Source string     `json:"source"`
	ISPs   []rawEntry `json:"isps"`
}

type loaded struct {
	list     []ISP
	byID     map[string]ISP
	prefixes map[string][]netip.Prefix
}

var (
	once       sync.Once
	state      *loaded
	overrideMu sync.RWMutex
	override   *loaded
)

func parsePrefixes(raw []string) []netip.Prefix {
	out := make([]netip.Prefix, 0, len(raw))
	for _, s := range raw {
		p, err := netip.ParsePrefix(strings.TrimSpace(s))
		if err != nil {
			continue
		}
		out = append(out, p.Masked())
	}
	return out
}

func build(raw rawCatalog) *loaded {
	l := &loaded{
		byID:     make(map[string]ISP, len(raw.ISPs)),
		prefixes: make(map[string][]netip.Prefix, len(raw.ISPs)),
	}
	for _, e := range raw.ISPs {
		id := normalizeID(e.ID)
		if id == "" || id == All {
			continue
		}
		prefixes := append(parsePrefixes(e.V4), parsePrefixes(e.V6)...)
		kind := e.Kind
		if kind == "" {
			kind = KindOther
		}
		item := ISP{
			ID:       id,
			NameEN:   e.NameEN,
			NameFA:   e.NameFA,
			Kind:     kind,
			ASNs:     e.ASNs,
			Prefixes: len(prefixes),
		}
		if _, dup := l.byID[id]; dup {
			continue
		}
		l.list = append(l.list, item)
		l.byID[id] = item
		if len(prefixes) > 0 {
			l.prefixes[id] = prefixes
		}
	}
	return l
}

func current() *loaded {
	overrideMu.RLock()
	o := override
	overrideMu.RUnlock()
	if o != nil {
		return o
	}
	once.Do(func() {
		var raw rawCatalog
		if err := json.Unmarshal(catalogJSON, &raw); err != nil {
			raw = rawCatalog{}
		}
		state = build(raw)
	})
	return state
}

// Catalog returns every known access network, in UI order.
func Catalog() []ISP {
	l := current()
	out := make([]ISP, len(l.list))
	copy(out, l.list)
	return out
}

// Get returns the catalog entry for id.
func Get(id string) (ISP, bool) {
	v, ok := current().byID[normalizeID(id)]
	return v, ok
}

// Known reports whether id names a catalog entry (All included).
func Known(id string) bool {
	id = normalizeID(id)
	if id == All {
		return true
	}
	_, ok := current().byID[id]
	return ok
}

func normalizeID(id string) string { return strings.ToLower(strings.TrimSpace(id)) }

// Sanitize canonicalizes a user-supplied selection: unknown ids are dropped,
// duplicates removed, the result sorted, and a selection containing All (or one
// that is empty) collapses to nil — the canonical "no restriction" value.
func Sanitize(ids []string) []string {
	if len(ids) == 0 {
		return nil
	}
	l := current()
	seen := make(map[string]struct{}, len(ids))
	out := make([]string, 0, len(ids))
	for _, raw := range ids {
		id := normalizeID(raw)
		if id == "" {
			continue
		}
		if id == All {
			return nil
		}
		if _, ok := l.byID[id]; !ok {
			continue
		}
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	if len(out) == 0 {
		return nil
	}
	sort.Strings(out)
	return out
}

// Prefixes returns the merged, de-duplicated prefix set of the given networks.
// A selection with no routable data yields none, which callers must treat as
// "cannot enforce" rather than "block everything".
func Prefixes(ids []string) []netip.Prefix {
	l := current()
	seen := make(map[netip.Prefix]struct{})
	out := make([]netip.Prefix, 0, 64)
	for _, id := range ids {
		for _, p := range l.prefixes[normalizeID(id)] {
			if _, dup := seen[p]; dup {
				continue
			}
			seen[p] = struct{}{}
			out = append(out, p)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Addr() == out[j].Addr() {
			return out[i].Bits() < out[j].Bits()
		}
		return out[i].Addr().Less(out[j].Addr())
	})
	return out
}

// Match returns the ids of every network announcing addr (best effort).
func Match(addr netip.Addr) []string {
	if !addr.IsValid() {
		return nil
	}
	addr = addr.Unmap()
	l := current()
	var out []string
	for _, item := range l.list {
		for _, p := range l.prefixes[item.ID] {
			if p.Contains(addr) {
				out = append(out, item.ID)
				break
			}
		}
	}
	return out
}

// Allows reports whether addr is permitted by the selection. An empty or
// unenforceable selection allows everything.
func Allows(ids []string, addr netip.Addr) bool {
	if len(ids) == 0 {
		return true
	}
	prefixes := Prefixes(ids)
	if len(prefixes) == 0 || !addr.IsValid() {
		return true
	}
	addr = addr.Unmap()
	for _, p := range prefixes {
		if p.Contains(addr) {
			return true
		}
	}
	return false
}

// InstallSnapshot swaps in a refreshed catalog (same shape as the embedded
// file). Invalid or empty payloads are rejected and leave the current data in
// place, so a bad refresh can never blank out an active restriction.
func InstallSnapshot(payload []byte) error {
	var raw rawCatalog
	if err := json.Unmarshal(payload, &raw); err != nil {
		return err
	}
	l := build(raw)
	total := 0
	for _, item := range l.list {
		total += item.Prefixes
	}
	if total == 0 {
		return ErrEmptySnapshot
	}
	overrideMu.Lock()
	override = l
	overrideMu.Unlock()
	return nil
}

// ErrEmptySnapshot is returned when a refreshed catalog carries no prefixes.
var ErrEmptySnapshot = errors.New("isp: refreshed catalog contains no prefixes")
