// Package isp holds the catalog of access networks (mobile operators, fixed
// ISPs, satellite providers) a client's configs can be locked to, together with
// the IP prefixes announced by each of them.
//
// The prefix snapshot in data/prefixes.json is generated by tools/ispgen from
// public routing data (RIPE NCC's asn.txt for the AS -> organisation mapping,
// ipverse/asn-ip and RIPEstat for the announced prefixes). It is embedded in the
// binary so a fresh panel works offline; RefreshFromNetwork can update it later.
package isp

import (
	_ "embed"
	"encoding/json"
	"net/netip"
	"sort"
	"strings"
	"sync"
)

// All is the pseudo-id meaning "every network is allowed". It is always the
// first entry of the catalog exposed to the UI.
const All = "all"

// Kind groups the catalog entries in the UI.
type Kind string

const (
	KindMobile    Kind = "mobile"
	KindFixed     Kind = "fixed"
	KindWireless  Kind = "wireless"
	KindSatellite Kind = "satellite"
)

// ISP is one selectable access network.
type ISP struct {
	ID     string   `json:"id"`
	NameEN string   `json:"nameEn"`
	NameFA string   `json:"nameFa"`
	Kind   Kind     `json:"kind"`
	ASNs   []uint32 `json:"asns"`
	// Prefixes is the number of announced IP prefixes currently known for this
	// ISP. Zero means the lock cannot be enforced for it (see Enforceable).
	Prefixes int `json:"prefixes"`
	// Note carries a UI-visible caveat, e.g. MVNOs that announce no address
	// space of their own and therefore cannot be told apart from their host
	// network.
	Note string `json:"note,omitempty"`
}

// Enforceable reports whether selecting this ISP actually restricts anything.
// An entry without prefixes is shown in the UI as unavailable instead of
// silently behaving like "all".
func (i ISP) Enforceable() bool { return i.Prefixes > 0 }

type catalogEntry struct {
	id     string
	nameEN string
	nameFA string
	kind   Kind
	note   string
}

// catalog is the curated, ordered list of networks. ASN -> prefix data lives in
// the generated snapshot and is joined in at load time by id.
var catalog = []catalogEntry{
	// Mobile network operators.
	{"mci", "Hamrah-e Aval (MCI)", "همراه اول", KindMobile, ""},
	{"irancell", "Irancell (MTN)", "ایرانسل", KindMobile, ""},
	{"rightel", "RighTel", "رایتل", KindMobile, ""},
	{"shatelmobile", "Shatel Mobile", "شاتل موبایل", KindMobile, ""},
	{"samantel", "SamanTel", "سامانتل", KindMobile, ""},
	{"taliya", "Taliya", "تالیا", KindMobile, ""},
	{"ariantel", "ArianTel", "آریانتل", KindMobile, "MVNO without its own announced prefixes"},
	{"lotustel", "LotusTel", "لوتوس‌تل", KindMobile, "MVNO without its own announced prefixes"},

	// Fixed-line ISPs (ADSL / VDSL / FTTH).
	{"tci", "TCI / Mokhaberat", "مخابرات ایران", KindFixed, ""},
	{"shatel", "Shatel", "شاتل", KindFixed, ""},
	{"asiatech", "Asiatech", "آسیاتک", KindFixed, ""},
	{"parsonline", "ParsOnline", "پارس‌آنلاین", KindFixed, ""},
	{"hiweb", "HiWEB", "های‌وب", KindFixed, ""},
	{"pishgaman", "Pishgaman", "پیشگامان", KindFixed, ""},
	{"fanava", "Fanava", "فن‌آوا", KindFixed, ""},
	{"respina", "Respina", "رسپینا", KindFixed, ""},
	{"sabanet", "SabaNet", "صبانت", KindFixed, ""},
	{"datak", "Datak", "داتک", KindFixed, ""},
	{"fanaptelecom", "FANAP Telecom", "فناپ تلکام", KindFixed, ""},
	{"afranet", "Afranet", "افرانت", KindFixed, ""},
	{"askhazar", "Andishe Sabz Khazar", "اندیشه سبز خزر", KindFixed, ""},
	{"rdg", "Rayaneh Danesh Golestan", "رایانه دانش گلستان", KindFixed, ""},

	// Wireless / TD-LTE.
	{"mobinnet", "Mobinnet", "مبین‌نت", KindWireless, ""},
}

//go:embed data/prefixes.json
var prefixesJSON []byte

type snapshotEntry struct {
	ASNs []uint32 `json:"asns"`
	V4   []string `json:"v4"`
	V6   []string `json:"v6"`
}

type snapshot struct {
	Source string                   `json:"source"`
	ISPs   map[string]snapshotEntry `json:"isps"`
}

type loaded struct {
	list     []ISP
	byID     map[string]ISP
	prefixes map[string][]netip.Prefix
}

var (
	once  sync.Once
	state *loaded
	// override holds a refreshed snapshot installed at runtime; nil means the
	// embedded one is in use.
	overrideMu sync.RWMutex
	override   *loaded
)

func parsePrefixes(raw []string) []netip.Prefix {
	out := make([]netip.Prefix, 0, len(raw))
	for _, s := range raw {
		p, err := netip.ParsePrefix(strings.TrimSpace(s))
		if err != nil {
			continue
		}
		out = append(out, p.Masked())
	}
	return out
}

func build(snap snapshot) *loaded {
	l := &loaded{
		byID:     make(map[string]ISP, len(catalog)),
		prefixes: make(map[string][]netip.Prefix, len(catalog)),
	}
	for _, e := range catalog {
		entry := snap.ISPs[e.id]
		prefixes := append(parsePrefixes(entry.V4), parsePrefixes(entry.V6)...)
		item := ISP{
			ID:       e.id,
			NameEN:   e.nameEN,
			NameFA:   e.nameFA,
			Kind:     e.kind,
			ASNs:     entry.ASNs,
			Prefixes: len(prefixes),
			Note:     e.note,
		}
		l.list = append(l.list, item)
		l.byID[e.id] = item
		if len(prefixes) > 0 {
			l.prefixes[e.id] = prefixes
		}
	}
	return l
}

func current() *loaded {
	overrideMu.RLock()
	o := override
	overrideMu.RUnlock()
	if o != nil {
		return o
	}
	once.Do(func() {
		var snap snapshot
		if err := json.Unmarshal(prefixesJSON, &snap); err != nil {
			snap = snapshot{ISPs: map[string]snapshotEntry{}}
		}
		state = build(snap)
	})
	return state
}

// Catalog returns every known access network, in UI order.
func Catalog() []ISP {
	l := current()
	out := make([]ISP, len(l.list))
	copy(out, l.list)
	return out
}

// Get returns the catalog entry for id.
func Get(id string) (ISP, bool) {
	v, ok := current().byID[normalizeID(id)]
	return v, ok
}

// Known reports whether id names a catalog entry (All included).
func Known(id string) bool {
	id = normalizeID(id)
	if id == All {
		return true
	}
	_, ok := current().byID[id]
	return ok
}

func normalizeID(id string) string { return strings.ToLower(strings.TrimSpace(id)) }

// Sanitize cleans a user-supplied selection: unknown ids are dropped, entries
// are de-duplicated and sorted, and a selection that contains All (or ends up
// covering every enforceable ISP, or is empty) collapses to nil — the canonical
// "no restriction" value.
func Sanitize(ids []string) []string {
	if len(ids) == 0 {
		return nil
	}
	l := current()
	seen := make(map[string]struct{}, len(ids))
	out := make([]string, 0, len(ids))
	for _, raw := range ids {
		id := normalizeID(raw)
		if id == "" {
			continue
		}
		if id == All {
			return nil
		}
		if _, ok := l.byID[id]; !ok {
			continue
		}
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	if len(out) == 0 {
		return nil
	}
	enforceable := 0
	for _, item := range l.list {
		if item.Enforceable() {
			enforceable++
		}
	}
	if len(out) >= enforceable {
		selectedEnforceable := 0
		for _, id := range out {
			if l.byID[id].Enforceable() {
				selectedEnforceable++
			}
		}
		if selectedEnforceable >= enforceable {
			return nil
		}
	}
	sort.Strings(out)
	return out
}

// Prefixes returns the merged, de-duplicated prefix set announced by the given
// ISPs. Selections that carry no routable data yield no prefixes, which callers
// must treat as "cannot enforce" rather than "block everything".
func Prefixes(ids []string) []netip.Prefix {
	l := current()
	seen := make(map[netip.Prefix]struct{})
	out := make([]netip.Prefix, 0, 64)
	for _, id := range ids {
		for _, p := range l.prefixes[normalizeID(id)] {
			if _, dup := seen[p]; dup {
				continue
			}
			seen[p] = struct{}{}
			out = append(out, p)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Addr() == out[j].Addr() {
			return out[i].Bits() < out[j].Bits()
		}
		return out[i].Addr().Less(out[j].Addr())
	})
	return out
}

// Match returns the ids of every catalog entry announcing addr, best-effort:
// an address outside all known ranges yields nil.
func Match(addr netip.Addr) []string {
	if !addr.IsValid() {
		return nil
	}
	addr = addr.Unmap()
	l := current()
	var out []string
	for _, item := range l.list {
		for _, p := range l.prefixes[item.ID] {
			if p.Contains(addr) {
				out = append(out, item.ID)
				break
			}
		}
	}
	return out
}

// Allows reports whether addr is permitted by the given selection. An empty or
// unenforceable selection allows everything.
func Allows(ids []string, addr netip.Addr) bool {
	if len(ids) == 0 {
		return true
	}
	prefixes := Prefixes(ids)
	if len(prefixes) == 0 {
		return true
	}
	if !addr.IsValid() {
		return true
	}
	addr = addr.Unmap()
	for _, p := range prefixes {
		if p.Contains(addr) {
			return true
		}
	}
	return false
}

// InstallSnapshot swaps in a refreshed prefix snapshot (as produced by
// tools/ispgen). Invalid payloads are rejected and leave the current data in
// place, so a bad refresh can never blank out an active restriction.
func InstallSnapshot(raw []byte) error {
	var snap snapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		return err
	}
	l := build(snap)
	total := 0
	for _, item := range l.list {
		total += item.Prefixes
	}
	if total == 0 {
		return errEmptySnapshot
	}
	overrideMu.Lock()
	override = l
	overrideMu.Unlock()
	return nil
}

type snapshotError string

func (e snapshotError) Error() string { return string(e) }

const errEmptySnapshot = snapshotError("isp: refreshed snapshot contains no prefixes")
